### PR TITLE
 BUGFIX getFoxyProductClasses returns FoxyHelper in some cases

### LINKED ISSUE #64: BUG FoxyHelper::getProductClasses doesn't always return array
**Describe the bug**
In some instances, `FoxyHelper::getProductClasses()` would return `FoxyHelper`.

**Expected behavior**
`FoxyHelper::getProductClasses()` should always return an array.

### PR DESCRIPTION
**Pull request by muskie9**
resolves #64

### CODE REVIEW

File: src/Model/FoxyHelper.php [hunk 1]
```diff
@@ -181,12 +188,13 @@ public function setProductClasses()
                 foreach (ClassInfo::subclassesFor($productClass) as $key => $class) {
                     $list[$key] = $class;
                 }
-                $this->foxy_product_classes =  $list;
-                return $this;
+
+                return $list;
```
Comment (muskie9) [inline src/Model/FoxyHelper.php]: @jsirish this is a change that seemed to resolve the issue. It may be related to how `array_reduce` works with it's closure param.

Comment (jsirish) [inline src/Model/FoxyHelper.php]: in other areas of this function, we're setting `foxy_product_classes` and returning `$this`. Should this line do the same?

Comment (muskie9) [reply src/Model/FoxyHelper.php]: I was utilizing the new method to build the array with the subclasses. Everything seemed to work, however I did see that `SiteTree::get()->filter('ClassName', ['MyBaseProductClass'])` will not return child classes of `MyBaseProductClass`, unless the `include_product_subclasses` config is set to true, or the subclasses are explicitly set in on the `product_classes` config.

Comment (muskie9) [reply src/Model/FoxyHelper.php]: The above description for the query is expected behavior as far as I know, just noting it.
